kind: pipeline
name: default

steps:
  - name: test
    image: maven:3.8.6-jdk-11
    environment:
      OPENWEATHERMAP_APPID:
        from_secret: appId
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B